### PR TITLE
chore(deps): nightly audit 2026-08-25

### PR DESCRIPTION
**Pull request by po4yka**
## Task contract

- Task ID: N/A (scheduled nightly dependency/security audit, not a portfolio task)
- Task record: N/A
- OpenSpec change: N/A
- Spec-not-required reason: dependency version bumps only, no behavior/spec change

## Summary

Nightly dependency and security audit across the Rust Cargo workspace (114 workspace-member crates under `native/rust/`) and the Kotlin/Gradle frontend (`gradle/libs.versions.toml`, ~13 modules). Only the SAFE bucket (patch-level bumps, non-crypto/network/async/FFI) is applied here; everything else is reported below for a human decision.

## Applied

**Rust** (`native/rust/Cargo.lock`, via `cargo update -p <crate>`):
- `log`: 0.4.33 → 0.4.34
- `maxminddb`: 0.30.0 → 0.30.3

**Gradle** (`gradle/libs.versions.toml`):
- `agp`: 9.3.1 → 9.3.2

Both are patch-only bumps that stay within the already-declared version requirements (`log = "0.4"`, `maxminddb = "0.30"`, `agp = "9.3.1"` → same 9.3.x line). No crate/dependency in this list touches crypto, networking, async runtime, or JNI/FFI surfaces. A full-repo sweep found no `build.gradle.kts` file that pins a dependency version outside the centralized catalog, so the AGP bump is the only Gradle file that needed editing.

## Security

RUSTSEC advisories found by `cargo audit` (raw scan) — all four are **already tracked and waived** in `native/rust/deny.toml` / `native/rust/advisory-waivers.toml` with owner, rationale, and an expiry date; none are new, and none are resolved by this PR's SAFE updates:

| RUSTSEC ID | Severity | Crate | Resolved by this PR? | Waiver expires |
|---|---|---|---|---|
| RUSTSEC-2023-0071 | CVSS 3.1 5.9 (Medium) — Marvin Attack timing side-channel | `rsa` 0.9.10 / 0.10.0-rc.18 (via Arti and russh) | No | 2026-11-02 |
| RUSTSEC-2025-0141 | Unmaintained | `bincode` 2.0.1 (transitive via Arti) | No | 2026-11-02 |
| RUSTSEC-2025-0069 | Unmaintained | `daemonize` 0.5.0 (isolated to `ripdpi-cli`'s daemonize feature) | No | 2026-10-11 |
| RUSTSEC-2024-0436 | Unmaintained | `paste` 1.0.15 (compile-time only, via netlink-packet-core) | No | 2026-10-11 |

`cargo deny check` passes (`advisories ok, bans ok, licenses ok, sources ok`) with only pre-existing warn-level output: 89 "multiple-versions" duplicate-crate warnings (expected in a workspace this size; `bans.multiple-versions = "warn"` by design) and one governance note — the `RUSTSEC-2025-0141` ignore entry in `deny.toml` no longer matches any crate in the current lock graph (`advisory-not-detected`), worth a cleanup pass to confirm `bincode` is still reachable or drop the stale waiver.

Nothing here required a build/version change to resolve, so no new waiver or Cargo.toml edit was made.

## Needs review

Minor-version bumps and anything touching crypto, networking, async runtime, or JNI/FFI — withheld regardless of semver level per policy.

**Rust:**
- `boring` / `tokio-boring`: `=5.1.0` → 5.2.0 — exact-pinned BoringSSL FFI bindings; `docs/design/reality-boringssl-patch.md` documents six hand-declared BoringSSL symbols in `ripdpi-vless`'s Reality TLS path that a bump could silently break. Needs a symbol-diff check before bumping.
- `russh`: `=0.62.6` → 0.63.1 — SSH/crypto relay transport, exact-pinned. This is the crate tracked by the RUSTSEC-2023-0071 waiver above (`docs/tasks/issues/unpin-russh-after-rsa-advisory-fix.md`) — worth checking whether 0.63.x moves off the RC RustCrypto chain (`rsa`, `ed25519-dalek`, `curve25519-dalek`, `p256`/`p384`/`p521`, `pkcs1`, `ssh-key`) and resolves the advisory.
- `constant_time_eq`: 0.4.2 → 0.5.0 — timing-safe comparison primitive (crypto), needs a `Cargo.toml` edit (outside current `^0.4` range).
- `blake3`: 1.8.5 → 1.8.7 — crypto hash used in `ripdpi-shadowsocks`. Patch-level and within the existing `^1` range, but withheld because it's a crypto primitive.
- `arti-client` / `tor-rtcompat`: 0.44.0 → 0.45.0 — Tor client network stack, pinned as a pair.
- `smoltcp`: 0.13.1 → 0.14.0 — TUN/IP stack core, networking.
- `similar`: 3.1.2 → 3.2.0 — minor bump (non-sensitive crate, withheld only because it crosses a minor boundary).

**Gradle:**
- `okhttp` / `okhttp-dnsoverhttps` / `okhttp-mockwebserver`: 5.4.0 → 5.5.0 — HTTP client, networking surface, withheld regardless of semver.
- `protobuf-javalite`: 4.35.1 → 4.36.0 — minor bump on the wire-serialization library backing diagnostics/relay contracts.
- Gradle wrapper: 9.6.1 → 9.7.1 — minor bump.
- `compose-preview-plugin` (`ee.schimke.composeai.preview`): 1.4.0 → 1.34.0 — **30 minor releases behind**; large enough drift to warrant a dedicated look rather than a blind bump (may not be strict-semver across that span).
- `androidx-navigation-compose`: 2.9.8 → 2.10.0-rc01 — no stable minor release yet, noted only.
- Several other AndroidX artifacts (`benchmark`, `biometric`, `camerax`, `datastore`(-preferences), `glance`(-appwidget/material3), `lifecycle-*`, `work`) have newer alpha/beta/RC releases but are already on the latest **stable** version — no action needed, listed only so the outdated-dependency sweep is documented as complete.

## Major

No major-version bumps are actionable right now:

- **Rust:** every workspace dependency with an available upgrade stays within its current major version; nothing crossed a major boundary.
- **Gradle:** `leakcanary-android` (2.14 → 3.0-alpha-9) and `robolectric` (4.16.1 → 4.17-beta-4) have next-major/next-minor lines in prerelease only — no stable release to move to yet. Kotlin (compiler/Compose/serialization plugins, 2.4.10) and AGP's 9.4/9.5 lines are likewise RC/alpha-only beyond the patch applied here.

## Conflicts

- No Gradle cross-module version divergence found: all ~13 modules resolve dependencies exclusively through the single centralized `gradle/libs.versions.toml` catalog. A repo-wide sweep of every `build.gradle.kts` found zero inline/hardcoded dependency versions overriding the catalog.
- Full transitive-constraint resolution (a `./gradlew :app:dependencies`-style sweep per module, to catch a transitive version diverging from a declared one) could not be run in this sandbox: `ripdpi.compileSdk = 37` has no published Android SDK platform package yet (`platforms;android-37` does not exist upstream as of this run), so AGP cannot configure any Android module here. This is an environment limitation, not a finding — worth a follow-up run somewhere with the real SDK installed.

## Other findings (not a dependency issue, flagged for visibility)

This PR's diff is dependency-only, but CI on this PR shows several red checks — all trace back to pre-existing issues already on `main` at this PR's base commit (`ed5d4e8`), confirmed unrelated to the dependency bumps:

- `cargo check --workspace` fails to compile `ripdpi-tls-spoof` (`crates/ripdpi-tls-spoof/src/inject.rs:359`): calls `RandomState::new().build_hasher()` without `use std::hash::BuildHasher;` in scope, and (depending on target-scope/feature unification) a `socket2::Type::RAW` reference also fails to resolve. Reproduced via `git stash` before any change in this PR.
- **`architecture-health`** (native hotspot/LoC budget gate) and **`rust-workspace-tests`** both fail on the same pre-existing budget overrun: `native/rust/crates/ripdpi-monitor-engine/src/session/lifecycle/start.rs` measures 112 lines against a 111-line limit (`[OVER]`). Confirmed already red on `main`'s own CI run for this exact commit (`ed5d4e8`, run [32698799598](https://github.com/po4yka/RIPDPI/actions/runs/32698799598)).
- **`gradle-static-analysis`** fails on a pre-existing detekt `TooGenericExceptionCaught` violation in `core/service/src/main/kotlin/com/poyka/ripdpi/services/VpnServiceSessionCleanup.kt:68` (`catch (stopFailure: Throwable)`), introduced by commit `5b64c03` on 2026-08-21 — days before this PR and untouched by it. It shows as "skipped" on `main`'s last push-triggered CI run only because that run's change-detection route didn't touch Kotlin files; the violation itself predates this PR.
- **`CI preflight barrier`** fails only as a downstream consequence of the two required-gate failures above (`Release expensive jobs after required gates pass`), not an independent issue.
- **`relay-interoperability`** fails with `error[E0432]: unresolved import crate::ShadowTlsLoopback` in `crates/ripdpi-shadowtls/src/loopback.rs:514` — `ShadowTlsLoopback` is re-exported from `lib.rs` only under `#[cfg(feature = "test-server")]`, and the specific multi-package test-compile selection this CI job uses (`--package ripdpi-xhttp --package ripdpi-vless --package ripdpi-hysteria2 --package ripdpi-tuic --package ripdpi-shadowtls --package ripdpi-anytls --package ripdpi-masque --package ripdpi-cloudflare-origin --package ripdpi-naiveproxy`) doesn't activate that feature for `ripdpi-shadowtls` under Cargo's feature unification, even though the crate compiles fine in isolation (`cargo test -p ripdpi-shadowtls --features test-server` passes). Reproduced by running the exact failing command against an isolated worktree of this PR's base commit (`ed5d4e8`) — identical error, confirming it predates this PR.
- **`rust-lint`** fails a separate `ripdpi-tls-spoof` governance gate: the unsafe-boundary-allowlist scan (`ci/unsafe-boundary-allowlist.toml`, policy in `docs/rust-soundness-policy.md`) reports `crates/ripdpi-tls-spoof/src/inject.rs:309 pattern=mem::zeroed` as a new, un-allowlisted unsafe pattern — a second, distinct pre-existing issue in the same already-broken file (`inject.rs`), unrelated to the missing-`BuildHasher`-import compile error noted above and to this PR's dependency bumps.
- **`JNI API snapshot check`** fails on a large, pre-existing `ripdpi-diagnostics-contracts` public-API drift: the committed snapshot still has many types at the crate root (`ripdpi_diagnostics_contracts::StrategyProbeReport`, `TransportPivotRecommendation`, etc.) while the current source has moved them into a `ripdpi_diagnostics_contracts::types` submodule, and dropped a few items (`CONNECTION_CONCURRENCY_CLASSIFIER_VERSION`, `EXECUTION_PLAN_VERSION`, `STRATEGY_PROBE_METHODOLOGY_VERSION`, `StrategyProbeDomainOutcome`) outright. This is a source-vs-snapshot mismatch that predates this PR by construction — nothing in this PR touches `ripdpi-diagnostics-contracts` or any code that could reshape its public API — but it does mean the committed API snapshot needs regenerating separately.

All seven are left untouched to keep this PR dependency-only and reviewable; each needs a separate, unrelated fix (a missing import, a one-line LoC trim or budget adjustment, a `@Suppress`/exception-narrowing decision on the detekt finding, a feature-unification fix for the `ripdpi-shadowtls` test-server re-export, an unsafe-boundary-allowlist entry or restructure for the `mem::zeroed` use in `ripdpi-tls-spoof`, and a `ripdpi-diagnostics-contracts` API snapshot regeneration).

## Evidence

- `cargo audit --json` (Rust, raw RUSTSEC scan) — 2 vulnerability entries / 3 unmaintained warnings, all pre-existing and waived (see Security section).
- `cargo deny check --hide-inclusion-graph` — `advisories ok, bans ok, licenses ok, sources ok`.
- `cargo update -p log -p maxminddb` — applied the two Rust SAFE bumps.
- `cargo check --workspace --locked --exclude ripdpi-tls-spoof` — clean, confirms the rest of the workspace still builds after the SAFE bumps (the excluded crate has the pre-existing unrelated failure above).
- Gradle: outdated/plugin versions and cross-module-conflict checks done via `gradle/libs.versions.toml` + Maven Central / Google Maven / Gradle Plugin Portal metadata queries (no inline version overrides found in any `build.gradle.kts`); full AGP-driven dependency-resolution build could not run here (see Conflicts).

## Checklist

- [x] No baseline files extended (detekt, lint, LoC) — none touched
- [x] Native ABI matrix not broken — no native build config changed, only dependency patch versions
- [x] Non-rooted device path unaffected — no VPN/root code touched
- [ ] `just task-check` — not run; this PR isn't tied to a portfolio task ID (see Task contract)
- [x] No work marked complete without evidence — see Evidence section above

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by po4yka** [comment]
Superseded by #446.
